import type {
  UploadCompleteResult,
  UploadUrlResult,
  VaultEntry,
} from "./schemas.js";

/**
 * Minimal client interface the manager needs. Avoids importing the concrete
 * `VaultClient` so this file stays trivially testable with a stub.
 */
export interface UploadManagerClient {
  createUploadUrl(input: {
    parentId?: string | null;
    name: string;
    contentType: string;
    size: number;
  }): Promise<UploadUrlResult>;
  completeUpload(input: {
    blobName: string;
    parentId?: string | null;
    name: string;
    contentType?: string;
  }): Promise<UploadCompleteResult>;
}

export type UploadFileState =
  | { status: "pending"; bytesUploaded: 0 }
  | { status: "uploading"; bytesUploaded: number }
  | { status: "completed"; bytesUploaded: number; entry: VaultEntry }
  | { status: "error"; bytesUploaded: number; error: Error }
  | { status: "canceled"; bytesUploaded: number };

export interface UploadHandle {
  /** Stable id, generated by the manager — not the future entry id. */
  readonly id: string;
  readonly name: string;
  readonly size: number;
  readonly type: string;
  readonly parentId: string | null;
  /** Mutated in place; subscribe to `change` to react. */
  state: UploadFileState;
  /** Cancel an in-flight or pending upload. No-op once completed. */
  cancel(): void;
}

export type UploadEvents = {
  /** Fired on any handle state transition AND on add/remove. */
  change: () => void;
  completed: (handle: UploadHandle) => void;
  error: (handle: UploadHandle) => void;
};

export interface UploadManagerOptions {
  /** Max parallel in-flight uploads. Default 3. */
  concurrency?: number;
  /** Reject `add()` calls when the queue would exceed this. Default 20. */
  maxFiles?: number;
  /** Reject files larger than this (bytes). Default Infinity (server enforces). */
  maxFileSize?: number;
}

interface InternalHandle extends UploadHandle {
  data: File;
  controller: AbortController;
}

/**
 * Tiny pub/sub. Avoids pulling `node:events` into browser bundles.
 */
class Emitter<E extends Record<string, (...args: any[]) => void>> {
  private listeners: { [K in keyof E]?: Set<E[K]> } = {};
  on<K extends keyof E>(event: K, fn: E[K]): () => void {
    (this.listeners[event] ??= new Set()).add(fn);
    return () => this.listeners[event]?.delete(fn);
  }
  protected emit<K extends keyof E>(event: K, ...args: Parameters<E[K]>): void {
    this.listeners[event]?.forEach((fn) => {
      try {
        (fn as (...a: unknown[]) => void)(...(args as unknown[]));
      } catch {
        /* listeners must not break the manager */
      }
    });
  }
}

const isBrowser =
  typeof window !== "undefined" && typeof XMLHttpRequest !== "undefined";

function newId(): string {
  if (typeof crypto !== "undefined" && typeof crypto.randomUUID === "function") {
    return crypto.randomUUID();
  }
  // Cheap fallback for older runtimes — only used outside of browsers/Node 19+.
  return `up-${Date.now().toString(36)}-${Math.random().toString(36).slice(2, 10)}`;
}

/**
 * Drives the two-step direct-upload flow (createUploadUrl → PUT bytes →
 * completeUpload) for many files concurrently, with progress, cancel, and
 * restriction checks. Framework-agnostic; UI bindings (Pinia, React, etc.)
 * subscribe to `change`/`completed`/`error`.
 *
 * Browser: PUT goes through XMLHttpRequest so `upload.onprogress` reports
 *          real byte counts.
 * Node:    PUT goes through fetch (no granular progress — bytesUploaded
 *          flips from 0 to size on success).
 */
export class UploadManager extends Emitter<UploadEvents> {
  private handles: InternalHandle[] = [];
  private active = new Set<string>();
  private opts: Required<UploadManagerOptions>;

  constructor(
    private client: UploadManagerClient,
    opts: UploadManagerOptions = {},
  ) {
    super();
    this.opts = {
      concurrency: opts.concurrency ?? 3,
      maxFiles: opts.maxFiles ?? 20,
      maxFileSize: opts.maxFileSize ?? Number.POSITIVE_INFINITY,
    };
  }

  list(): UploadHandle[] {
    return this.handles;
  }

  /**
   * Enqueue one file. Returns the handle, or `null` if the file was rejected
   * by a restriction (queue full, file too big). Restriction failures are
   * not error states on a handle — the file simply never enters the queue.
   */
  add(input: { file: File; parentId?: string | null }): UploadHandle | null {
    if (this.handles.length >= this.opts.maxFiles) return null;
    if (input.file.size > this.opts.maxFileSize) return null;

    const handle: InternalHandle = {
      id: newId(),
      name: input.file.name,
      size: input.file.size,
      type: input.file.type || "application/octet-stream",
      parentId: input.parentId ?? null,
      state: { status: "pending", bytesUploaded: 0 },
      data: input.file,
      controller: new AbortController(),
      cancel: () => {},
    };
    handle.cancel = () => this.cancel(handle.id);

    this.handles.push(handle);
    this.emit("change");
    queueMicrotask(() => this.schedule());
    return handle;
  }

  /**
   * Remove a handle from the queue. Cancels first if in flight. Completed
   * handles can also be removed (this is how UIs clear "Done" rows).
   */
  remove(id: string): void {
    const idx = this.handles.findIndex((h) => h.id === id);
    if (idx === -1) return;
    this.cancel(id);
    this.handles.splice(idx, 1);
    this.emit("change");
  }

  /** Cancel without removing — handle stays so the UI can show "canceled". */
  cancel(id: string): void {
    const handle = this.handles.find((h) => h.id === id);
    if (!handle) return;
    if (
      handle.state.status === "completed" ||
      handle.state.status === "canceled"
    ) {
      return;
    }
    handle.controller.abort();
    handle.state = {
      status: "canceled",
      bytesUploaded: handle.state.bytesUploaded,
    };
    this.emit("change");
  }

  cancelAll(): void {
    for (const h of this.handles) this.cancel(h.id);
  }

  /** Drop every handle, canceling in-flight first. Useful on logout. */
  clear(): void {
    this.cancelAll();
    this.handles = [];
    this.emit("change");
  }

  // ── internals ──────────────────────────────────────────────────────────

  private schedule(): void {
    while (this.active.size < this.opts.concurrency) {
      const next = this.handles.find((h) => h.state.status === "pending");
      if (!next) return;
      this.active.add(next.id);
      this.run(next).finally(() => {
        this.active.delete(next.id);
        // Pump again — the just-finished slot may unblock another file.
        queueMicrotask(() => this.schedule());
      });
    }
  }

  private async run(handle: InternalHandle): Promise<void> {
    if (handle.controller.signal.aborted) return;

    handle.state = { status: "uploading", bytesUploaded: 0 };
    this.emit("change");

    try {
      const ticket = await this.client.createUploadUrl({
        parentId: handle.parentId,
        name: handle.name,
        contentType: handle.type,
        size: handle.size,
      });
      if (handle.controller.signal.aborted) return;

      await this.put(handle, ticket);
      if (handle.controller.signal.aborted) return;

      const completed = await this.client.completeUpload({
        blobName: ticket.blobName,
        parentId: handle.parentId,
        name: handle.name,
        contentType: handle.type,
      });

      handle.state = {
        status: "completed",
        bytesUploaded: handle.size,
        entry: completed.entry,
      };
      this.emit("change");
      this.emit("completed", handle);
    } catch (err) {
      // If the abort fired mid-flight, prefer "canceled" over "error" so
      // UIs can show the right affordance.
      if (handle.controller.signal.aborted) {
        handle.state = {
          status: "canceled",
          bytesUploaded: handle.state.bytesUploaded,
        };
        this.emit("change");
        return;
      }
      handle.state = {
        status: "error",
        bytesUploaded: handle.state.bytesUploaded,
        error: err instanceof Error ? err : new Error(String(err)),
      };
      this.emit("change");
      this.emit("error", handle);
    }
  }

  private put(handle: InternalHandle, ticket: UploadUrlResult): Promise<void> {
    return isBrowser
      ? this.putXHR(handle, ticket)
      : this.putFetch(handle, ticket);
  }

  private putXHR(
    handle: InternalHandle,
    ticket: UploadUrlResult,
  ): Promise<void> {
    return new Promise((resolve, reject) => {
      const xhr = new XMLHttpRequest();
      xhr.open("PUT", ticket.uploadUrl, true);
      xhr.setRequestHeader("Content-Type", handle.type);
      for (const [k, v] of Object.entries(ticket.requiredHeaders ?? {})) {
        xhr.setRequestHeader(k, v);
      }

      xhr.upload.onprogress = (e) => {
        if (!e.lengthComputable) return;
        // Reuse the existing state object rather than reallocating, but
        // emit `change` so reactive consumers re-read.
        if (handle.state.status === "uploading") {
          handle.state = { status: "uploading", bytesUploaded: e.loaded };
          this.emit("change");
        }
      };

      xhr.onload = () => {
        if (xhr.status >= 200 && xhr.status < 300) resolve();
        else
          reject(
            new Error(
              `Direct upload PUT failed for ${handle.name}: ${xhr.status} ${xhr.statusText}`,
            ),
          );
      };
      xhr.onerror = () =>
        reject(new Error(`Direct upload PUT network error for ${handle.name}`));
      xhr.onabort = () =>
        reject(new Error(`Direct upload PUT aborted for ${handle.name}`));

      handle.controller.signal.addEventListener("abort", () => xhr.abort());
      xhr.send(handle.data);
    });
  }

  private async putFetch(
    handle: InternalHandle,
    ticket: UploadUrlResult,
  ): Promise<void> {
    const res = await fetch(ticket.uploadUrl, {
      method: "PUT",
      headers: {
        "Content-Type": handle.type,
        ...ticket.requiredHeaders,
      },
      body: handle.data,
      signal: handle.controller.signal,
    });
    if (!res.ok) {
      throw new Error(
        `Direct upload PUT failed for ${handle.name}: ${res.status} ${res.statusText}`,
      );
    }
    // No granular progress on fetch; bump to full on completion.
    handle.state = { status: "uploading", bytesUploaded: handle.size };
    this.emit("change");
  }
}
