packages:
  - "apps/*"
  - "packages/*"

allowBuilds:
  argon2: true
  better-sqlite3: true
  esbuild: true
  msw: true
  vue-demi: true

catalog:
  zod: "^4.4.3"

minimumReleaseAgeExclude:
  - '@cloudflare/workers-types@5.20260726.1'
