import { vi } from "vitest"

vi.mock("./lib/env", () => ({
  getServerConfig: vi.fn().mockReturnValue({
    PORT: 3001,
    ALLOWED_ORIGIN: "http://localhost:3000",
    BLOB_PROVIDER: "azure",
    AZURE_STORAGE_CONNECTION_STRING: "",
    AZURE_STORAGE_ACCOUNT_NAME: "",
    AZURE_STORAGE_ACCOUNT_KEY: "",
    AZURE_STORAGE_CONTAINER_NAME: "vault",
    R2_ACCOUNT_ID: "",
    R2_ACCESS_KEY_ID: "",
    R2_SECRET_ACCESS_KEY: "",
    R2_BUCKET_NAME: "vault",
    R2_ENDPOINT: "",
    COSMOS_DB_ENDPOINT: "https://localhost:8081",
    COSMOS_DB_KEY: "",
    COSMOS_DB_DATABASE: "vault",
    COSMOS_DB_CONTAINER: "vault_entries",
    COSMOS_DB_LOOKUP_CONTAINER: "vault_lookup",
    COSMOS_DB_AUTH_CONTAINER: "vault_auth",
    AUTH_SECRET: "test-auth-secret",
    JWT_SECRET: "test-jwt-secret",
    ACCESS_EXPIRES_SECONDS: 900,
    REFRESH_EXPIRES_SECONDS: 604800,
    LOGIN_STALL_MS: 250,
    SMTP_HOST: "localhost",
    SMTP_PORT: 1025,
    SMTP_SECURE: false,
    SMTP_USER: "",
    SMTP_PASS: "",
    SMTP_URL: "",
    EMAIL_FROM: "noreply@vault.app",
    APP_URL: "http://localhost:3000",
    MAX_UPLOAD_MB: 100,
    RATE_LIMIT_DISABLED: undefined,
  }),
  resetConfigs: vi.fn(),
}))
